"""Vegetation layout and mesh generation used by the map-painting GUI."""

from __future__ import annotations

import math
import random
import re
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image

TERRAIN_SIZE = 512.0
KINDS = ("grass", "bush", "tree")
BASE_SPACING = {"grass": 0.45, "bush": 1.5, "tree": 3.8}
MAX_PLACEMENTS = {"grass": 60_000, "bush": 12_000, "tree": 4_000}
BEGIN = "    <!-- BEGIN PAINTED VEGETATION: managed by tools/place_obstacles.py -->"
END = "    <!-- END PAINTED VEGETATION -->"


@dataclass(frozen=True)
class Plant:
    kind: str
    x: float
    y: float
    z: float
    scale: float
    yaw: float


def load_elevation(path: Path) -> np.ndarray:
    elevation = np.asarray(Image.open(path), dtype=np.float64)
    if elevation.ndim != 2 or min(elevation.shape) < 2:
        raise ValueError("terrain must be a two-dimensional elevation image")
    return elevation - np.nanmin(elevation)


def terrain_height(elevation: np.ndarray, x: float, y: float) -> float:
    col = int(round((x + TERRAIN_SIZE / 2) * (elevation.shape[1] - 1) / TERRAIN_SIZE))
    row = int(round((TERRAIN_SIZE / 2 - y) * (elevation.shape[0] - 1) / TERRAIN_SIZE))
    return float(elevation[np.clip(row, 0, elevation.shape[0] - 1), np.clip(col, 0, elevation.shape[1] - 1)])


def _inside(mask: np.ndarray, x: float, y: float) -> bool:
    col = int((x + TERRAIN_SIZE / 2) * mask.shape[1] / TERRAIN_SIZE)
    row = int((TERRAIN_SIZE / 2 - y) * mask.shape[0] / TERRAIN_SIZE)
    return 0 <= row < mask.shape[0] and 0 <= col < mask.shape[1] and bool(mask[row, col])


def plants_from_masks(
    masks: dict[str, np.ndarray], elevation: np.ndarray, density: float = 1.0, seed: int = 4207
) -> list[Plant]:
    """Cover every painted region with a jittered, staggered lattice."""
    if not 0.2 <= density <= 3.0:
        raise ValueError("density must be between 0.2 and 3.0")
    rng = random.Random(seed)
    plants: list[Plant] = []
    scale_ranges = {"grass": (0.70, 1.35), "bush": (0.70, 1.35), "tree": (0.75, 1.30)}
    for kind in KINDS:
        mask = np.asarray(masks[kind], dtype=bool)
        spacing = BASE_SPACING[kind] / math.sqrt(density)
        row_spacing = spacing * math.sqrt(3.0) / 2.0
        candidates: list[tuple[float, float]] = []
        y = -TERRAIN_SIZE / 2 + row_spacing / 2
        row_index = 0
        while y < TERRAIN_SIZE / 2:
            x = -TERRAIN_SIZE / 2 + spacing / 2 + (row_index % 2) * spacing / 2
            while x < TERRAIN_SIZE / 2:
                if _inside(mask, x, y):
                    jitter = spacing * 0.18
                    jx, jy = x + rng.uniform(-jitter, jitter), y + rng.uniform(-jitter, jitter)
                    candidates.append((jx, jy) if _inside(mask, jx, jy) else (x, y))
                x += spacing
            y += row_spacing
            row_index += 1
        if len(candidates) > MAX_PLACEMENTS[kind]:
            raise ValueError(
                f"painted {kind} region needs {len(candidates):,} objects; "
                f"reduce density or area below {MAX_PLACEMENTS[kind]:,}"
            )
        low, high = scale_ranges[kind]
        for x, y in candidates:
            plants.append(
                Plant(kind, x, y, terrain_height(elevation, x, y), rng.uniform(low, high), rng.random() * math.tau)
            )
    return plants


class ObjWriter:
    def __init__(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        self.file = path.open("w", encoding="ascii")
        self.file.write("# Batched vegetation generated by tools/place_obstacles.py\nmtllib vegetation.mtl\n")
        self.vertex = 1
        self.normal = 1

    def close(self) -> None:
        self.file.close()

    def material(self, name: str) -> None:
        self.file.write(f"usemtl {name}\n")

    def triangle(self, points: list[tuple[float, float, float]]) -> None:
        (x0, y0, z0), (x1, y1, z1), (x2, y2, z2) = points
        ux, uy, uz = x1 - x0, y1 - y0, z1 - z0
        vx, vy, vz = x2 - x0, y2 - y0, z2 - z0
        nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
        length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
        nx, ny, nz = nx / length, ny / length, nz / length
        for x, y, z in points:
            self.file.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
        self.file.write(f"vn {nx:.6f} {ny:.6f} {nz:.6f}\n")
        v, n = self.vertex, self.normal
        self.file.write(f"f {v}//{n} {v + 1}//{n} {v + 2}//{n}\n")
        self.vertex += 3
        self.normal += 1

    def quad(self, points: list[tuple[float, float, float]]) -> None:
        self.triangle([points[0], points[1], points[2]])
        self.triangle([points[0], points[2], points[3]])

    def cylinder(self, x: float, y: float, z: float, radius: float, height: float, sides: int = 8) -> None:
        bottom = [(x + radius * math.cos(i * math.tau / sides), y + radius * math.sin(i * math.tau / sides), z) for i in range(sides)]
        top = [(x + radius * 0.72 * math.cos(i * math.tau / sides), y + radius * 0.72 * math.sin(i * math.tau / sides), z + height) for i in range(sides)]
        for i in range(sides):
            self.quad([bottom[i], bottom[(i + 1) % sides], top[(i + 1) % sides], top[i]])

    def ellipsoid(self, x: float, y: float, z: float, rx: float, ry: float, rz: float, yaw: float) -> None:
        rings, sides = 4, 8
        vertices: list[list[tuple[float, float, float]]] = []
        cy, sy = math.cos(yaw), math.sin(yaw)
        for ring in range(rings + 1):
            phi = -math.pi / 2 + math.pi * ring / rings
            layer = []
            for side in range(sides):
                theta = math.tau * side / sides
                lx, ly = rx * math.cos(phi) * math.cos(theta), ry * math.cos(phi) * math.sin(theta)
                layer.append((x + cy * lx - sy * ly, y + sy * lx + cy * ly, z + rz * math.sin(phi)))
            vertices.append(layer)
        for ring in range(rings):
            for side in range(sides):
                self.quad([
                    vertices[ring][side], vertices[ring][(side + 1) % sides],
                    vertices[ring + 1][(side + 1) % sides], vertices[ring + 1][side],
                ])

    def octahedron(self, x: float, y: float, z: float, rx: float, ry: float, rz: float) -> None:
        top, bottom = (x, y, z + rz), (x, y, z - rz)
        ring = [(x + rx, y, z), (x, y + ry, z), (x - rx, y, z), (x, y - ry, z)]
        for index in range(4):
            self.triangle([top, ring[index], ring[(index + 1) % 4]])
            self.triangle([bottom, ring[(index + 1) % 4], ring[index]])


def _write_materials(path: Path) -> None:
    colors = {
        "grass_a": (0.12, 0.33, 0.055), "grass_b": (0.20, 0.42, 0.08),
        "bush_a": (0.055, 0.20, 0.035), "bush_b": (0.10, 0.30, 0.055),
        "bush_c": (0.16, 0.36, 0.08), "trunk": (0.19, 0.075, 0.025),
        "leaf_a": (0.04, 0.17, 0.025), "leaf_b": (0.075, 0.25, 0.04),
        "leaf_c": (0.13, 0.31, 0.055),
    }
    with path.open("w", encoding="ascii") as output:
        for name, (r, g, b) in colors.items():
            output.write(f"newmtl {name}\nKa {r:.3f} {g:.3f} {b:.3f}\nKd {r:.3f} {g:.3f} {b:.3f}\nKs 0.01 0.01 0.01\n\n")


def _write_grass(writer: ObjWriter, plant: Plant, rng: random.Random) -> None:
    for blade in range(5):
        angle = plant.yaw + blade * math.tau / 5 + rng.uniform(-0.18, 0.18)
        width, height = 0.085 * plant.scale, rng.uniform(0.55, 0.95) * plant.scale
        dx, dy = math.cos(angle) * width, math.sin(angle) * width
        lean_x, lean_y = math.cos(angle + 1.3) * height * 0.12, math.sin(angle + 1.3) * height * 0.12
        writer.material("grass_a" if blade % 2 else "grass_b")
        writer.quad([
            (plant.x - dx, plant.y - dy, plant.z), (plant.x + dx, plant.y + dy, plant.z),
            (plant.x + lean_x + dx * 0.12, plant.y + lean_y + dy * 0.12, plant.z + height),
            (plant.x + lean_x - dx * 0.12, plant.y + lean_y - dy * 0.12, plant.z + height),
        ])


def _write_bush(writer: ObjWriter, plant: Plant, rng: random.Random) -> None:
    for lobe in range(5):
        angle = plant.yaw + lobe * 2.4
        radius = (0.22 if lobe else 0.0) * plant.scale
        scale = plant.scale * rng.uniform(0.78, 1.08)
        writer.material(("bush_a", "bush_b", "bush_c")[lobe % 3])
        writer.ellipsoid(
            plant.x + radius * math.cos(angle), plant.y + radius * math.sin(angle),
            plant.z + (0.48 + 0.09 * (lobe % 2)) * plant.scale,
            0.52 * scale, 0.42 * scale, 0.48 * scale, angle,
        )


def _write_tree(writer: ObjWriter, plant: Plant, rng: random.Random) -> None:
    trunk_h, trunk_r = 3.1 * plant.scale, 0.20 * plant.scale
    writer.material("trunk")
    writer.cylinder(plant.x, plant.y, plant.z, trunk_r, trunk_h)
    for lobe in range(5):
        angle = plant.yaw + lobe * 2.1
        radius = (0.38 if lobe else 0.0) * plant.scale
        writer.material(("leaf_a", "leaf_b", "leaf_c")[lobe % 3])
        writer.ellipsoid(
            plant.x + radius * math.cos(angle), plant.y + radius * math.sin(angle),
            plant.z + (3.25 + 0.28 * (lobe % 3)) * plant.scale,
            rng.uniform(0.85, 1.25) * plant.scale, rng.uniform(0.75, 1.15) * plant.scale,
            rng.uniform(0.85, 1.20) * plant.scale, angle,
        )


def generate_model(plants: list[Plant], model_dir: Path, seed: int = 4207) -> dict[str, int]:
    mesh_dir = model_dir / "meshes"
    mesh_dir.mkdir(parents=True, exist_ok=True)
    _write_materials(mesh_dir / "vegetation.mtl")
    counts = {kind: 0 for kind in KINDS}
    by_kind = {kind: [plant for plant in plants if plant.kind == kind] for kind in KINDS}
    for kind in KINDS:
        writer = ObjWriter(mesh_dir / f"{kind}.obj")
        rng = random.Random(seed + KINDS.index(kind) * 1009)
        render = {"grass": _write_grass, "bush": _write_bush, "tree": _write_tree}[kind]
        for plant in by_kind[kind]:
            render(writer, plant, rng)
        writer.close()
        counts[kind] = len(by_kind[kind])

    collision_writer = ObjWriter(mesh_dir / "collision.obj")
    collision_count = 0
    for plant in plants:
        if plant.kind == "bush":
            collision_writer.octahedron(
                plant.x, plant.y, plant.z + .43 * plant.scale,
                .43 * plant.scale, .43 * plant.scale, .43 * plant.scale,
            ); collision_count += 1
        elif plant.kind == "tree":
            collision_writer.cylinder(plant.x, plant.y, plant.z, .20 * plant.scale, 3.1 * plant.scale)
            collision_count += 1
        elif plant.kind == "grass":
            # Low enough for the rover's wheels (8 cm radius) to climb over, so
            # a tuft adds rolling friction instead of acting like a fence post.
            collision_writer.cylinder(plant.x, plant.y, plant.z, .11 * plant.scale, .03 * plant.scale)
            collision_count += 1
    collision_writer.close()
    semantic_labels = {"grass": 50, "bush": 17, "tree": 28}
    visuals = "\n".join(
        f'    <visual name="{kind}"><plugin filename="gz-sim-label-system" name="gz::sim::systems::Label"><label>{semantic_labels[kind]}</label></plugin><geometry><mesh><uri>model://painted_vegetation/meshes/{kind}.obj</uri></mesh></geometry></visual>'
        for kind in KINDS if by_kind[kind]
    )
    sdf = (
        '<?xml version="1.0"?>\n<sdf version="1.10">\n  <model name="painted_vegetation">\n'
        '    <static>true</static>\n  <link name="vegetation">\n' + visuals + "\n"
        + ('    <collision name="vegetation_collision"><geometry><mesh><uri>model://painted_vegetation/meshes/collision.obj</uri></mesh></geometry></collision>\n' if collision_count else '')
        + "\n  </link>\n  </model>\n</sdf>\n"
    )
    (model_dir / "model.sdf").write_text(sdf)
    (model_dir / "model.config").write_text(
        '<?xml version="1.0"?>\n<model><name>Painted vegetation</name><version>1.0</version>'
        '<sdf version="1.10">model.sdf</sdf><description>Batched vegetation from the map painter.</description></model>\n'
    )
    return counts


def install_world_include(world_path: Path) -> None:
    text = world_path.read_text()
    block = BEGIN + '\n    <include><name>painted_vegetation</name><uri>model://painted_vegetation</uri></include>\n' + END
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(text):
        text = pattern.sub(block, text)
    else:
        text = text.replace("  </world>", block + "\n  </world>")
    world_path.write_text(text)


def remove_legacy_vegetation(world_path: Path) -> int:
    """Remove old individual vegetation includes after explicit GUI selection."""
    text = world_path.read_text()
    pattern = re.compile(
        r"\s*<include>\s*<name>(?:grass|bush|tree)_\d+</name>\s*"
        r"<uri>model://(?:grass|bush|tree)</uri>.*?</include>", re.DOTALL
    )
    updated, count = pattern.subn("", text)
    if count:
        world_path.write_text(updated)
    return count
